# Generated by Django 4.2.2 on 2023-06-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='instamojo_id',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
